"""bang

Revision ID: 04f030ce41e8
Revises: 
Create Date: 2022-11-13 16:46:59.655380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04f030ce41e8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('barcode', sa.String(length=32), nullable=False),
    sa.Column('brand', sa.String(length=32), nullable=True),
    sa.Column('serving_size', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_food_barcode'), 'food', ['barcode'], unique=False)
    op.create_index(op.f('ix_food_name'), 'food', ['name'], unique=False)
    op.create_table('profile',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=96), nullable=False),
    sa.Column('default_meals', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_email'), 'profile', ['email'], unique=False)
    op.create_index(op.f('ix_profile_username'), 'profile', ['username'], unique=False)
    op.create_table('diary_entry',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('profile_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nutrition_record',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('per_100', sa.Float(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('food_id', sa.String(length=36), nullable=True),
    sa.Column('profile_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['food_id'], ['food.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meal',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=True),
    sa.Column('diaryentry_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['diaryentry_id'], ['diary_entry.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('food_entry',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('food_id', sa.String(length=36), nullable=True),
    sa.Column('meal_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['food_id'], ['food.id'], ),
    sa.ForeignKeyConstraint(['meal_id'], ['meal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('food_entry')
    op.drop_table('meal')
    op.drop_table('nutrition_record')
    op.drop_table('diary_entry')
    op.drop_index(op.f('ix_profile_username'), table_name='profile')
    op.drop_index(op.f('ix_profile_email'), table_name='profile')
    op.drop_table('profile')
    op.drop_index(op.f('ix_food_name'), table_name='food')
    op.drop_index(op.f('ix_food_barcode'), table_name='food')
    op.drop_table('food')
    # ### end Alembic commands ###
