"""added default_meals to Profile

Revision ID: e3d6b519f47e
Revises: 7df67db86fbf
Create Date: 2022-11-10 14:12:29.608286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3d6b519f47e'
down_revision = '7df67db86fbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('default_meals', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile', 'default_meals')
    # ### end Alembic commands ###
